# Generated by Django 5.2.10 on 2026-01-29 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MySpaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_song_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_song_external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_song_preview_url', models.URLField(blank=True, null=True)),
                ('profile_song_album_art', models.URLField(blank=True, null=True)),
                ('auto_play', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myspace_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MySpace Profile',
                'verbose_name_plural': 'MySpace Profiles',
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField(default=0)),
                ('external_id', models.CharField(max_length=100)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('album_art', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('myspace_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='myspace.myspaceprofile')),
            ],
            options={
                'verbose_name': 'Playlist Song',
                'verbose_name_plural': 'Playlist Songs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
