# Generated by Django 5.2.10 on 2026-02-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0002_myspaceprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myspaceprofile',
            name='avatar',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
