from rest_framework import serializers
from .models import MySpaceProfile, PlaylistSong
from .deezer_utils import get_preview_url


class PlaylistSongSerializer(serializers.ModelSerializer):
    # Custom field that calls the duration_formatted property from the model
    # Converts milliseconds (180000) to readable format ("3:00")
    duration = serializers.CharField(source='duration_formatted', read_only=True)
    
    # Fresh preview URL fetched from iTunes (primary) or Deezer (fallback)
    preview_url = serializers.SerializerMethodField()

    class Meta:
        # Tells serializer which database table to work with
        model = PlaylistSong
        
        # Which fields to include in JSON response
        # These map directly to model fields (except 'duration' which uses the property)
        fields = [
            'id',
            'title',
            'artist',
            'duration',        # Human-readable ("3:00")
            'duration_ms',     # Raw milliseconds (180000)
            'external_id',     # Spotify/Deezer track ID
            'preview_url',     # 30-second preview URL (fetched fresh)
            'album_art',       # Album cover image URL
            'order',           # Playlist position (0, 1, 2...)
        ]
        
        # Fields that can't be modified from frontend (auto-generated by database)
        read_only_fields = ['id']
    
    def get_preview_url(self, obj):
        """
        Fetch fresh preview URL from iTunes (primary) or Deezer (fallback).
        iTunes URLs are stable and don't expire like Deezer's signed tokens.
        """
        # Try to get fresh URL from iTunes/Deezer
        fresh_url = get_preview_url(obj.title, obj.artist, obj.external_id)
        if fresh_url:
            return fresh_url
        # Fallback to stored URL (SoundHelix samples)
        return obj.preview_url


class PublicMySpaceProfileSerializer(serializers.ModelSerializer):
    """
    Public-facing serializer that matches the frontend's expected format.
    Uses camelCase field names that the React app expects.
    
    GET /api/myspace/<username>/
    """
    # Profile song fields (camelCase for frontend)
    songTitle = serializers.CharField(source='profile_song_title', read_only=True)
    songArtist = serializers.CharField(source='profile_song_artist', read_only=True)
    
    # Profile customization fields (defaults for now)
    mood = serializers.SerializerMethodField()
    customBio = serializers.SerializerMethodField()
    theme = serializers.SerializerMethodField()
    wallpaper = serializers.SerializerMethodField()
    sliderStyle = serializers.SerializerMethodField()
    
    # Playlist with full song data including preview_url
    playlist = PlaylistSongSerializer(source='playlist_songs', many=True, read_only=True)
    
    class Meta:
        model = MySpaceProfile
        fields = [
            'songTitle',
            'songArtist', 
            'mood',
            'customBio',
            'theme',
            'wallpaper',
            'sliderStyle',
            'playlist',
        ]
    
    def get_mood(self, obj):
        """Return mood - placeholder for now"""
        return "chillin"
    
    def get_customBio(self, obj):
        """Return custom bio - placeholder for now"""
        return ""
    
    def get_theme(self, obj):
        """Return theme - placeholder for now"""
        return "classic"
    
    def get_wallpaper(self, obj):
        """Return wallpaper - placeholder for now"""
        return "none"
    
    def get_sliderStyle(self, obj):
        """Return slider style - placeholder for now"""
        return 1


class MySpaceProfileSerializer(serializers.ModelSerializer):
    # Nested serializer - includes entire playlist as array of song objects
    # source='playlist_songs' comes from related_name in PlaylistSong model
    # many=True means "expect multiple songs, not just one"
    playlist = PlaylistSongSerializer(source='playlist_songs', many=True, read_only=True)
    
    # Pull username from related User model (self.user.username)
    username = serializers.CharField(source='user.username', read_only=True)

    # Custom method field - calls get_profile_song() below
    # Packages profile song data as clean nested object instead of flat fields
    profile_song = serializers.SerializerMethodField()

    class Meta:
        model = MySpaceProfile
        
        # All fields to include in JSON
        # Notice we include BOTH profile_song (nested object) AND individual fields
        # This gives frontend flexibility in how they access the data
        fields = [
            'id',
            'username',
            'profile_song',              # Nested: {title, artist, preview_url...}
            'profile_song_title',        # Flat: "Bohemian Rhapsody"
            'profile_song_artist',       # Flat: "Queen"
            'profile_song_external_id',
            'profile_song_preview_url',
            'profile_song_album_art',
            'auto_play',                 # Boolean: should song play on profile load?
            'playlist',                  # Array of song objects
            'created_at',
            'updated_at',
        ]
        read_only_fields = ['id', 'username', 'created_at', 'updated_at']

    def get_profile_song(self, obj):
        """
        Custom method for profile_song field.
        Instead of returning 5 separate fields, packages them into one object.
        Returns None if no profile song set.
        
        obj = the MySpaceProfile instance being serialized
        """
        if obj.profile_song_title:
            return {
                'title': obj.profile_song_title,
                'artist': obj.profile_song_artist,
                'external_id': obj.profile_song_external_id,
                'preview_url': obj.profile_song_preview_url,
                'album_art': obj.profile_song_album_art,
            }
        return None


class AddSongToPlaylistSerializer(serializers.Serializer):
    """
    Not a ModelSerializer - this is for INCOMING data validation only.
    When React sends POST request to add a song, these fields are required.
    """
    title = serializers.CharField(max_length=255)
    artist = serializers.CharField(max_length=255)
    duration_ms = serializers.IntegerField()
    external_id = serializers.CharField(max_length=100)
    
    # required=False means frontend doesn't have to send these
    # allow_null=True means they can explicitly send null
    preview_url = serializers.URLField(required=False, allow_null=True)
    album_art = serializers.URLField(required=False, allow_null=True)


class UpdateProfileSongSerializer(serializers.Serializer):
    """
    For updating the "currently vibing to" profile song.
    All fields optional so you can update just one field at a time.
    """
    title = serializers.CharField(max_length=255, required=False, allow_null=True)
    artist = serializers.CharField(max_length=255, required=False, allow_null=True)
    external_id = serializers.CharField(max_length=100, required=False, allow_null=True)
    preview_url = serializers.URLField(required=False, allow_null=True)
    album_art = serializers.URLField(required=False, allow_null=True)
    auto_play = serializers.BooleanField(required=False)