# Generated by Django 5.2.10 on 2026-02-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myspaceprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
