# Generated by Django 5.2.10 on 2026-02-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myspaceprofile',
            name='profile_song_album_art',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='myspaceprofile',
            name='profile_song_preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='album_art',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        # Note: AlterModelTable operations removed - tables already named correctly
    ]
