# 🟡 NATALIA - Auth & Users Lead
# 0001_initial.py - Initial database migration
"""
NOTE: This file is auto-generated by Django

When you run: python manage.py makemigrations users
Django will create this file based on your models.py

DO NOT write this manually - let Django generate it.

Natalia's responsibility:
1. Define models in models.py
2. Run: python manage.py makemigrations users
3. Review the generated migration
4. Run: python manage.py migrate

This placeholder shows what to expect, but Django creates the actual content.
Delete this file and run makemigrations after implementing models.py
"""

# Django will generate migration code here
